# Generated by Django 3.2.7 on 2021-11-23 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popups', '0003_popup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='popup',
            name='reinstatement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
